(define draw-perorin-square-limit (lambda (n frm)
	(clear-picture)
	(set-color #x0B6A4A)
	((square-limit (perorin 'frame) n) frm)
	(set-color #x0ffffff)
	((square-limit (perorin 'left-eye) n) frm)
	((square-limit (perorin 'right-eye) n) frm)
	((square-limit (perorin 'mouth) n) frm)
	(set-color #xCB361F)
	((square-limit (perorin 'tongue) n) frm)
))

(load "init.lsp")
(load "painter.scm")
(load "square-limit.scm")
(draw-perorin-square-limit 4 frm1)
